# Generated by Django 5.0.1 on 2024-01-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_apartmentrent_apartmentsell_delete_postsell'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentrent',
            name='token',
            field=models.CharField(editable=False, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='apartmentsell',
            name='token',
            field=models.CharField(editable=False, max_length=8, null=True, unique=True),
        ),
    ]
